In [10]:
import numpy as np
from scipy import stats

In [11]:
# stats.f_oneway?

#### Задача

In [12]:
# Провести дисперсионный анализ для определения того, есть ли различия среднего роста 
# среди взрослых футболистов, хоккеистов и штангистов.  
# Даны значения роста в трех группах случайно выбранных спортсменов: 
# Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. 
# Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. 
# Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.
# Сделать вывод для альфа 1% и 5%

In [13]:
# Решение: сформулируем нулевую гипотезу Н0: mu1=mu2=mu3/
# Проведем дисперсионный анализ и сравним результаты анализа 
# с уровнем aflpha=0.05 и alpha=0.01.
y_f = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y_f

array([173, 175, 180, 178, 177, 185, 183, 182])

In [14]:
y_h = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y_h

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [15]:
y_w = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y_w

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [16]:
stats.f_oneway(y_f,y_h,y_w)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

In [17]:
# В результате получили значение pvalue=0.010482206918698694. Мы видим, что 
# при alpha=0.05 различия среднего роста в групах 
# статистически значимы. И наоборот: при уровне alpha=0.01 разница среднего роста в группах не имеет
# выраженной статистической значимости.
# Вывод: в случае применения критерия Фишера-Снедекора уменьшение значения alpha ведет к 
# возрастанию вероятности ошибки второго рода и наоборот.